name: GISAutomation
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - rasterio
  - requests
  - dask
  - geopandas
  - rioxarray
  - shapely
  - pydantic
  - omegaconf
  - hydra-core
  - torchgeo
  - whitebox_tools
  - qgis
  - PCRaster

