name: GICAutomation
channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - numpy=1.23.2
  - rasterio=1.2.10
  - requests=2.28.1
  - fiona=1.8.22
  - dask=2022.12.0
  - geopandas=0.12.2
  - rioxarray=0.13.1
  - shapely
  - pydantic=1.10.7
  - omegaconf
  - hydra-core
  - torchgeo
  - whitebox_tools
  - qgis

