name: GISAuto
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - rasterio
  - requests
  - dask
  - geopandas
  - rioxarray
  - shapely
  - pydantic
  - omegaconf
  - hydra-core
  - torchgeo
  - whitebox_tools
  - qgis
  - PCRaster
  - pyyaml