## 
crop_tif:
 _target_ : util.crop_tif 
#  tif_file : None
 shapefile : C:\Users\abfernan\CrossCanFloodMapping\GISAutomation\data\BC_Quesnel.shp
#  output_file : None

clip_raster_to_polygon:
 _target_ : util.clip_raster_to_polygon
#  inputRaster : None 
 maskVector : C:\Users\abfernan\CrossCanFloodMapping\GISAutomation\data\BC_Quesnel.shp
#  outPath : None

# # Add a shpe file path to use as a mask for the raster extraction.
# mask: 'C:\Users\abfernan\CrossCanFloodMapping\GISAutomation\data\BC_Quesnel.shp' # str. Optional defaults to None.