## We can add a dictionary for every function to call from dc_extract module. 
# IMPORTANT: See dc_extract documentation for detailles. 
 ## Comment/UnComment to add/supress inputs to the function

dc_extrac_cog:
 _target_: dc_extract.extract_cog.extract_cog.extract_cog
 bbox: '-123.3250,51.9500,-120.1473,53.7507'
 bbox_crs: 'EPSG:4326'
 collections : 'cdem:dem'
# bbox: '-123.3250,51.9500,-120.1473,53.7507' #Format : 'xMinLeft, yMinLeft, xMaxRigh, yMaxRight' or 
# collection : 'cdem:dem' # sintax --> 'colection:asset'
# dc_extract_cog's list of params:
# bbox_crs: None #str
# field_value : None
# field_id : None #str
# geom_file: None #str
# resolution: None,# int
# method: 'nearest' #str ()
# out_crs: None #str
 out_dir: 'C:\Users\abfernan\CrossCanFloodMapping\GISAutomation\dc_output\example'
# suffix: None  # str
# datetime_filter: None # str
# resolution_filter: None # str
# overviews: False 
# debug: False
# mosaic: False 
# orderby: 'date' 
# desc: True

dc_search:
 _target_: dc_extract.describe.describe.search
 name: 'C:\Users\abfernan\CrossCanFloodMapping\GISAutomation\automationOutput\example\description.gpkg'
 bbox: '-123.3250,51.9500,-120.1473,53.7507'
#  urls: ['https://datacube.services.geo.ca/api']         
#  dt: None
 cols: 'cdem'
#  geojson: False


dc_describeCollections: 
 _target_: dc_extract.describe.describe.collections
 name: 'C:\Users\abfernan\CrossCanFloodMapping\GISAutomation\automationOutput\example\description.gpkg'
#  urls: ['https://datacube.services.geo.ca/api'] 
#  geojson : False 
#________________________________________________________________
# Values that can be shar ed by all functions:
date_time : None  # datetime_str_in_ISO_8601_with_Z. (ex. str --> '2011-08-12T20:17:46.384Z') Optional defaults to None. 